name: login-e2e

on:
  push:
    branches: [ main,new ]
  pull_request:
    branches: [ main,new ]

jobs:
  login-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend        
        run: npm ci

      - name: Run Cypress login tests
        working-directory: frontend
        run: npx cypress run --spec cypress/e2e/login.cy.ts
        continue-on-error: true
      - name: Generate Cypress HTML report
        if: always()
        working-directory: frontend
        run: npm run report:e2e

      - name: Upload Cypress HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-login-html-report
          path: frontend/cypress/reports/html
          if-no-files-found: ignore

      - name: Upload Cypress artifacts (screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-login-report
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos
          if-no-files-found: ignore
